name: Metrics
on:
  schedule:
    - cron: "30 10 * * 1,4"  # Lunes y Jueves 10:30 UTC (~07:30 Chile en horario estándar)
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: WilldiazRaM
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Santiago
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_traffic: yes
