name: Metrics
on:
  schedule:
    - cron: "30 10 * * 1,4"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: WilldiazRaM
          template: classic
          filename: metrics.svg
          base: header, activity, community, repositories, metadata
          config_timezone: America/Santiago

          # 🔽 Incluye repos privados
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          repositories_private: yes

          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_traffic: yes
